apiVersion: v1
kind: Service
metadata:
  name: blibkit-service
spec:
  selector:
    app: blinkit
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
